config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'homes#about'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :posts do
    resources :comments
    member do
      get 'like', to: 'posts#upvote'
      get 'dislike', to: 'posts#downvote'
    end
  end
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  validates :title, presence: true, uniqueness: true, length: {minimum: 5 }
  
  has_attached_file :image, styles: { medium: "700x600>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_votable
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :email, :password_confirmation, :current_password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  
  private
  def comment_params
    params.require(:comment).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    if params[:category].blank?
      @posts = Post.all.order("created_at DESC").page(params[:page]).per(5)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @posts = Post.where(category_id: @category_id).order("created_at DESC").page(params[:page]).per(5)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  # GET /posts/1/edit
  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
    @post.category_id = params[:category_id]
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @post.category_id = params[:category_id]
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @post }
    
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  #vote upvote
  def upvote
    @post.upvote_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end
  
  #vote downvote
  def downvote
    @post.downvote_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end
  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :author, :category_id, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private
  
  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_title">
      <strong>Title:</strong>
      <%= comment.title %>
    </p>
    <p class="comment_body">
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>
    <p class="comment_time">
      <strong>Create_Time:</strong>
      <%= time_ago_in_words(comment.created_at) %>
    </p>
  </div>
  <%= link_to "删除", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default" %>
</div>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, id: :comment_title %>
  </div>
  
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, id: :comment_body %>
  </div>
  
  <div class="field">
    <%= f.submit %>
  </div>  
<% end %>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= image_tag 'gutianle.jpg', size: "140x140", alt: "gutianle img", class: "img-circle" %>
    </div>
  </div>
  <div class="col-md-6">
    <h1>个人简历</h1>
    <ul>
      <li><p>一个刚刚才学习编程的菜鸟</p></li>
      <li></li>
      <li></li>
    </ul>
  </div> 
</div>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom book-footer">
  <p>Copyright@2018 <%= link_to "菜菜", about_path %>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">切换导航</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="navbar-nav navbar-left">
        <li><%= image_tag 'blog.jpg', size: "50x50", class: "navbar-brand img-circle" %></li>
        <li><%= link_to 'Mypost', root_path, class: "navbar-brand" %><li>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <% if user_signed_in? %>
          <li><%= link_to 'Add post', new_post_path %></li>
        <% end  %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
              <li>
                <%= link_to category.name, posts_path(category: category.name), class: "link" %>
              </li>
            <% end  %>
          </ul>
        </li>
        <li><%= link_to "About", about_path %></li>
        <li><a href="#">About</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right"> 
        <li><%= link_to 'Sign Up', new_user_registration_path, class: "glyphicon glyphicon-user" %></li>
        <% if user_signed_in? %> 
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %></li>
        <% else  %>
          <li><%= link_to 'Sign In', new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
        <% end  %>
      </ul>
    </div> 
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/nav' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, html: { multipart: true }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2> 
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= select_tag :category_id, options_for_select(@categories), { prompt: "select a Category"} %>
  </div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>
  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :post_author %>
  </div>
  <div class="field">
    <%= form.file_field :image %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
      <h1>Editing Post</h1>
      <%= render 'form', post: @post %>
      <%= link_to 'Show', @post %> |
      <%= link_to 'Back', posts_path %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
      <h1>Posts</h1>
      <% @posts.each do |post| %>
        <h3><%= link_to post.title, post_path(post) %></h3>
        <%= image_tag post.image.url(:medium) %>
        <p><%= post.content %> by <%= post.user.email %></p>
        <div class="btn btn-default">
          <span class="icon"><i class="glyphicon glyphicon-heart"></i></span>
          <span class="vote_count"><%= pluralize(post.get_upvotes.size, 'Like') %></span>
        </div>
        <div class="btn btn-default">
          <span class="icon"><i class="glyphicon glyphicon-heart-empty"></i></span>
          <span class="vote_count"><%= pluralize(post.get_downvotes.size, 'DisLike') %></span>  
        </div>  
        <%= link_to 'Edit', edit_post_path(post) %> |
        <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure"} %> 
      <% end %>
      <div><%= paginate @posts %></div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
      <h1>New Post</h1>
      <%= render 'form', post: @post %>
      <%= link_to 'Back', posts_path %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
      <h1>Show Post</h1>
      <%= image_tag @post.image.url(:medium) %>
      <h3><%= @post.title %></h3>
      <p><%= @post.content %></p>
      <p><%= @post.author %></p>
      <div id="comments">
        <h2><%= @post.comments.count %> Comments</h2>
        <%= render @post.comments %>
        <h3>Add a comment:</h3>
        <%= render 'comments/form' %>
      </div>
      <div class="panel-block likes data">
        <% if user_signed_in? %>
          <%= link_to like_post_path(@post), method: :get, class: "btn btn-default" do %>
            <span class="icon"><i class="glyphicon glyphicon-heart"></i></span>
            <span class="vote_count"><%= pluralize(@post.get_upvotes.size, 'Like') %></span>
          <% end %>
          <%= link_to dislike_post_path(@post), method: :get, class: "btn btn-default" do %>
            <span class="icon"><i class="glyphicon glyphicon-heart-empty"></i></span>
            <span class="vote_count"><%= pluralize(@post.get_downvotes.size, 'disLike') %></span>
          <% end %>
        <% else %>
          <%= link_to like_post_path(@post), method: :get, class: "btn btn-default" do %>
            <span class="icon"><i class="glyphicon glyphicon-heart"></i></span>
            <span class="vote_count"><%= pluralize(@post.get_upvotes.size, 'Like') %></span>
          <% end %>
        <% end %>
      </div>
      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Back', posts_path %>
    </div>
  </div>
</div>